# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9698f0af7c713a34126c8103db60c632a0943dd853bf68157771df35d0f710e4f3c6fb372659faa357b239113a8d66decec6133bb213ea8d85ccb38a0cec9cf

test:
  secret_key_base: 648d61986517baf7901eaff2f7828939191f7da9cde3502be0b0f962d5fd32afd3ed171aba8b140d41fa060aafadea1af54a5afc0f5971778cbc5ddc29c2fc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
